python3 preprocessing/DIRE/compute_dire.py \
--model_path models/256x256_diffusion_uncond.pt \
--attention_resolutions 32,16,8 \
--class_cond False \
--diffusion_steps 1000 --dropout 0.1 --image_size 256 --learn_sigma True --noise_schedule linear --num_channels 256 \
--num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True \
--images_dir RealFakeDB_tiny/train \
--recons_dir RealFakeDB_tiny/recons_train \
--dire_dir RealFakeDB_tiny/dire_train \
--batch_size 16 --num_samples 2000  --timestep_respacing ddim20 --use_ddim True \
--has_subfolder True